FROM python:3.8

ARG workdir=/opt/rainy
RUN mkdir -p ${workdir}
WORKDIR ${workdir}

RUN pip3 install torch torchvision torchaudio
RUN apt-get clean\
    && apt-get update\
    && apt-get install -y vim\
    && apt-get install -y git
COPY . .
RUN pip3 install -r docker/requirements.txt

CMD [ "/bin/bash" ]
